import { FazBsElement } from "../bs-element";
import { JSX } from "solid-js/jsx-runtime";
export declare class FilterableItem {
    name: string;
    value: any;
    category?: string | undefined;
}
export type FilterCallback = (query: string) => FilterableItem[];
export type InitCallback = (filterbox: FazBsInputFilterbox) => void;
export declare class FazBsInputFilterbox extends FazBsElement {
    autocomplete: string;
    items: FilterableItem[];
    label: string;
    name: string;
    value: string;
    selectedName: string;
    displayFilter: boolean;
    filtering: boolean;
    filterCallback: FilterCallback | string | undefined;
    initCallback: InitCallback | string | undefined;
    private container;
    private inputName;
    private inputValue;
    private prefixId;
    private buffer;
    private filterDelay;
    private filterTimeoutId;
    private beOverTimeoutId;
    private overListGroup;
    private inputHasFocus;
    constructor();
    private get containerId();
    private get inputId();
    private get inputValueId();
    private get listContainer();
    get classNames(): string;
    defaultFilterCallback(query: string): FilterableItem[];
    getCategories(filteredItems: FilterableItem[]): string[];
    get filteredItems(): FilterableItem[];
    filterUncategorizedItems(filteredItems: FilterableItem[]): FilterableItem[];
    filteredItemsByCategory(category: string, filteredItems: FilterableItem[]): FilterableItem[];
    doFilter(_: Event): void;
    showFilter(): void;
    clearFilter(): void;
    clearFilterTimeout(): void;
    verifySelectedValue(): void;
    hasFilterableItems(): boolean;
    setItems(items: FilterableItem[]): void;
    beOverListGroup(): void;
    leaveListGroup(): void;
    activateOption(e: Event): void;
    deactivateOption(e: Event): void;
    selectOption(e: Event): void;
    filterCategorizedResultItems(category: string, filteredItems: FilterableItem[]): JSX.Element[];
    get results(): JSX.Element;
    renderUncategorizedResults(filteredItems: FilterableItem[]): JSX.Element[];
    renderCategorizedResults(filteredItems: FilterableItem[]): JSX.Element[];
    renderFilterContainer(): JSX.Element | undefined;
    renderFilteringMessage(): JSX.Element | undefined;
    renderInputName(): JSX.Element;
    renderInputValue(): JSX.Element;
    show(): void;
    afterShow(): void;
}
//# sourceMappingURL=filterbox.d.ts.map